create table if not exists public.app_analytics_events (
  id bigint generated by default as identity primary key,
  advisor_code text not null,
  session_id text not null,
  event_name text not null check (event_name in ('session_start', 'tab_view', 'tab_duration', 'action')),
  tab_name text,
  duration_seconds integer,
  action_name text,
  device text,
  created_at timestamptz not null default now()
);

alter table public.app_analytics_events enable row level security;
revoke all on table public.app_analytics_events from anon, authenticated;
create index if not exists idx_app_analytics_created_at on public.app_analytics_events(created_at desc);
create index if not exists idx_app_analytics_advisor on public.app_analytics_events(advisor_code, created_at desc);
create index if not exists idx_app_analytics_session on public.app_analytics_events(session_id);

notify pgrst, 'reload schema';
